# Generated by Django 4.1.3 on 2022-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nn_architecture', '0002_imagetrainingclassification_tag_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetrainingclassification',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='category for the image (train, test or validation)'),
        ),
    ]
