version: '3.7'
services:
  conv-server:
    build: ./cnn-server
    container_name: cnn-server
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    # volumes:
    #   - .:/code
    # depends_on:
    #   - db
    network_mode: "host"
    # networks:
    #   - compose_network
  client:
    build: ./cnn-client
    container_name: client
    depends_on:
      - "conv-server"
    restart: always
    network_mode: "host"
    # networks:
    #   - compose_network

networks:
  compose_network:

volumes:
  mysql_data: