version: '3.7'
services:
  mysql:
    container_name: djangodb
    
    build:
      dockerfile: ./mysql/Dockerfile
      # args:
      #   - MYSQL_DATABASE=${MYSQL_DATABASE}
      #   - MYSQL_USER=${MYSQL_USER}
      #   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      #   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  conv-server:
    build: ./cnn-server
    command: python /code/manage.py runserver 0.0.0.0:8000
    depends_on:
      - mysql
    # networks:
    #   - compose_network
  client:
    build: ./cnn-client
    depends_on:
      - "conv-server"
    # networks:
    #   - compose_network
  # gateway:
  #   build: .
  #   depends_on:
  #     - "conv-server"
  #   network_mode: "host"

networks:
  compose_network:

volumes:
  mysql_data: