# Generated by Django 4.1.3 on 2022-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('img_name', models.CharField(blank=True, max_length=200, verbose_name='image name')),
                ('img', models.ImageField(upload_to='test_images/', verbose_name='the image')),
                ('accuracy', models.CharField(blank=True, max_length=200, verbose_name='accuracy from the convolution')),
                ('loss', models.CharField(blank=True, max_length=200, verbose_name='loss about the model training')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
            },
        ),
    ]
