# Generated by Django 4.1.3 on 2022-11-26 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='updated_at',
            new_name='deleted_at',
        ),
        migrations.CreateModel(
            name='HistoricalClassification',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('img_name', models.CharField(blank=True, max_length=200, verbose_name='image name')),
                ('img', models.TextField(max_length=100, verbose_name='the image')),
                ('accuracy', models.CharField(blank=True, max_length=200, verbose_name='accuracy from the convolution')),
                ('loss', models.CharField(blank=True, max_length=200, verbose_name='loss about the model training')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Classification',
                'verbose_name_plural': 'historical Classifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
