# Generated by Django 4.1.3 on 2022-11-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0004_remove_classification_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='img',
            field=models.ImageField(upload_to='upload_images/', verbose_name='the image'),
        ),
    ]
