# Generated by Django 4.1.3 on 2022-11-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0005_alter_classification_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='img',
            field=models.ImageField(upload_to='cnn/images', verbose_name='the image'),
        ),
    ]
