# Generated by Django 4.1.3 on 2022-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0008_alter_classification_accuracy_healthy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='accuracy_healthy',
            field=models.CharField(blank=True, max_length=200, verbose_name='healthy leaf'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='loss_nitrogen',
            field=models.CharField(blank=True, max_length=200, verbose_name='low nitrogen leaf'),
        ),
        migrations.AlterField(
            model_name='historicalclassification',
            name='accuracy_healthy',
            field=models.CharField(blank=True, max_length=200, verbose_name='healthy leaf'),
        ),
        migrations.AlterField(
            model_name='historicalclassification',
            name='loss_nitrogen',
            field=models.CharField(blank=True, max_length=200, verbose_name='low nitrogen leaf'),
        ),
    ]
